config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "cities#index"

  resources :cities, only: [:index, :show] do
    get 'average_monthly_aqi', to: 'cities#average_monthly_aqi'
  end


end

app/models/air_quality_log.rb
class AirQualityLog < ApplicationRecord
  belongs_to :city

  def pollutants_data
    dat = ""
    concentrations.each_with_index do |gas, ind|
      comma = ind < concentrations.count - 1 ? ",": ""
      dat = "#{dat}#{gas[0].capitalize}: #{gas[1]}#{comma} "
    end
    dat.strip
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord

  has_many  :air_quality_logs, -> { order(recorded_on: :desc) }

  def coordinates
    "#{latitude.round(2)}, #{longitude.round(2)}"
  end

  def latest_aqi
    air_quality_logs.first
  end

  def average_aqi_index
    if air_quality_logs.present?
      air_quality_logs.sum(:index)/air_quality_logs.count
    else
      "No data"
    end
  end

  def average_monthly_aqi #returns a hash of format key = month/year, value = aqi
    if air_quality_logs.present?
      logs = air_quality_logs.group_by { |m| m.recorded_on.month }
      average_hash = {}
      logs.each do |monthly_log|
        monthly_average = (monthly_log[1].map{|x| x.index}.sum).to_f/monthly_log[1].count
        year = monthly_log[1].sample.recorded_on.year
        average_hash["#{monthly_log[0]}/#{year}"] = monthly_average.round(2)
      end
      average_hash
    else
      "No data"
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from ActiveRecord::RecordNotFound, with: :error_not_found

  def error_not_found
    render file: "#{Rails.root}/public/404.html", status: 404
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  before_action :find_city, except: [:index]

  def index
    @cities = City.all
  end

  def average_monthly_aqi
    @average_aqi_hash = @city.average_monthly_aqi
  end

  private

  def find_city
    @city = City.find_by(id: params[:city_id] || params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cities/average_monthly_aqi.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: center;
  padding: 8px;
}

tr:nth-child(odd) {
  background-color: #dddddd;
}
</style>
</head>
<body>

<h2><%= link_to @city.name, city_path(@city) %> - average monthly AQI</h2>
<h3><%= link_to "home", root_path %></h3>


<table>
  <% if @city.air_quality_logs.present? %>
    <tr>
      <td>Month</td>
      <td>Average AQI</td>
    </tr>
    <% @average_aqi_hash.each do |monthly_average| %>
      <% month = monthly_average[0].split('/').first.to_i %>
      <% year = monthly_average[0].split('/').last %>
      <tr>
        <td><%= "#{Date::MONTHNAMES[month]} - #{year}"%> </td>
        <td><%= monthly_average[1] %></td>
      </tr>
    <% end %>
  <% else %>
    No data
  <% end %>

</table>

</body>
</html>

app/views/cities/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: center;
  padding: 8px;
}

tr:nth-child(odd) {
  background-color: #dddddd;
}
</style>
</head>
<body>

<h2>Cities</h2>

<table>
  <tr>
    <td>Name</td>
    <td>Co-ordinates</td>
    <td>Latest AQI</td>
    <td>Concentrations</td>
    <td>Latest data fetched on</td>
    <td>Historic average AQI</td>
  </tr>
  <% @cities.each do |city| %>
  <tr>
    <td><%= link_to city.name, city_path(city) %></td>
    <td><%= city.coordinates %></td>
    <% if city.latest_aqi.present? %>
      <td><%= city.latest_aqi.index %></td>
      <td><%= city.latest_aqi.pollutants_data%></td>
      <td><%= city.latest_aqi.recorded_on.strftime("%d-%b-%y, %H:%M %Z")%></td>
      <td><%= city.average_aqi_index%></td>
    <% else %>
      <td>No data</td>
      <td>No data</td>
      <td>No data</td>
      <td>No data</td>
    <% end %>
  </tr>
  <% end %>

</table>

</body>
</html>

app/views/cities/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: center;
  padding: 8px;
}

tr:nth-child(odd) {
  background-color: #dddddd;
}
</style>
</head>
<body>

<h2><%= @city.name %> - historic logs</h2>
<h3><%= link_to "average monthly data", city_average_monthly_aqi_path(@city) %></h3>
<h3><%= link_to "home", root_path %></h3>

<table>
  <% if @city.air_quality_logs.present? %>
    <tr>
      <td>Date</td>
      <td>AQI</td>
      <td>Concentrations</td>
    </tr>
    <% @city.air_quality_logs.each do |aqi_log| %>
      <tr>
        <td><%= aqi_log.recorded_on.strftime("%d-%b-%y, %H:%M %Z")%> </td>
        <td><%= aqi_log.index %></td>
        <td><%= aqi_log.pollutants_data %></td>
      </tr>
    <% end %>
  <% else %>
    No data
  <% end %>

</table>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aqi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>